name: pneumonia-ml
channels:
  - conda-forge
dependencies:
  - python=3.9
  - pandas
  - numpy
  - scikit-learn
  - matplotlib
  - seaborn
  - jupyterlab
  - imbalanced-learn
  - shap
  - openpyxl  # For Excel support